# Is this server connected to BungeeCord?
# If set to true, spigot features that exist in bungee won't be active.
bungee: false

# Who can join the server while the server is whitelisted?
whitelist:
     active: false
     players: []

# Banwave settings
banwave:
     duration: 5m 
     # Who should be excluded from all banwaves? Exclusions are in UUID
     exclusions: []
     
     
notes:


# If any specific timezone has been set by the player, it will appear here.
playerTimeZones: