main: com.matchamc.core.bukkit.BukkitMain
name: MatchaMC
version: 0.1
description: Base plugin for server - Spigot/Paper
softdepend: [LiteBans, AntiAura, SuperVanish]
author: [Wilsoon, ironinventor]
commands:
     clearchat:
         description: Clears the chat
         usage: /<command>
     mutechat:
         description: Mutes the chat
         usage: /<command>
     socialspy:
         description: Toggle SocialSpy
         usage: /<command>
     message:
         description: Private Message a Player
         usage: /<command> <player> <message>
         aliases: [msg, w, whisper, pm]
     nightvision:
         description: Toggles Night Vision
         usage: /<command>
         aliases: [nv]
     override:
         description: Well...
         usage: "Don't even bother."
     playertime:
         description: Player Time
         usage: /<command> <time of day>
         aliases: [ptime]
     playerweather:
         description: Player Weather
         usage: /<command> <weather>
         aliases: [pweather]
     reply:
         description: Reply to the last player that messaged you
         usage: /<command> <message>
         aliases: [r]
     heal:
         description: Heal a player
         usage: /<command> <player>
     feed:
         description: Feed a player
         usage: /<command> <player>
     gamemode:
         description: Sets the gamemode of a player
         usage: /<command> <gamemode> <player>
     god:
         description: Sets the god status of a player
         usage: /<command> <player>
     logininfo:
         description: Retrieves the login information of a player
         usage: /<command> <player>
     speed:
         description: Change the walk/fly speed of a player
         usage: /<command> <walk/fly> <speed> <player>
     skull:
         description: Get the skull of a player
         usage: /<command> <player>
     teleport:
         description: Teleport a player to a coordinate/another player
         usage: /<command> <player/coordinates>
         aliases: [tp]
     teleporthere:
         description: Teleport a player to your location
         usage: /<command> <player>
         aliases: [tphere]
     timezone:
         description: Sets your own personal timezone
         usage: /<command> <timezone offset>
         aliases: [tz]
     time:
         description: Changes the world time
         usage: /<command> <time of day>
     togglepm:
         description: Toggles the ability to private message
         usage: /<command>
     weather:
         description: Changes the world weather
         usage: /<command> <weather>
     whitelist:
         description: Queries the whitelist to check/modify who can join the server while whitelisted
         usage: /<command> <on/off/add/remove/view> <player>
     # StaffCore commands
     alerts:
         description: Enables or disables the ability for you to view anticheat alerts
         usage: /<command>
     banwave:
         description: Queries the banwave to check/modify who is queued for the next banwave
         usage: /<command> <add/remove/list/nextwave> <name>
     chathistory:
         description: Queries a player's chat history
         usage: /<command> <name>
     dbalerts:
         description: Enables or disables the ability for you to view anticheat dragback alerts
         usage: /<command>
     freeze:
         description: Freeze/Unfreeze a player
         usage: /<command> <player>
     note:
         desscription: Creates a note
         usage: /<command> <note>
     notes:
         description: View your notes
         usage: /<command>
     punish:
         description: Punish a player
         usage: /<command> <player>
     report:
         description: Report a player
         usage: /<command> <player>
     reports:
         description: View your reports / View all reports created by players
         usage: /<command>
     srtp:
         description: Randomly teleport to a player
         usage: /<command>
         aliases: [staffrtp]